name: Deploy Amber

on:
  push:
    branches: [main]
    paths:
      - "apps/amber/**"
      - "libs/engine/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-pages.yml
    with:
      app-dir: apps/amber
      project-name: amber
      needs-engine: true
      needs-foliage: true
    secrets: inherit
