name: Deploy Post Migrator

on:
  push:
    branches: [main]
    paths:
      - "workers/post-migrator/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-worker.yml
    with:
      worker-dir: workers/post-migrator
      run-tests: true
    secrets: inherit
